# -*- coding: utf-8 -*-
"""twitter_api_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zQXngWoBVVyHUBju7oJHDUukjIEkRxdf
"""

import requests
import os
import json

bearer_token = ''

search_url = "https://api.twitter.com/2/tweets/search/recent"

query_params = {'query': '(from:twitterdev -is:retweet) OR #food','start_time': '2022-09-30T00:00:00Z','end_time': '2022-10-05T10:00:00Z'}

def bearer_oauth(r):
    """
    Method required by bearer token authentication.
    """

    r.headers["Authorization"] = f"Bearer {bearer_token}"
    r.headers["User-Agent"] = "v2RecentSearchPython"
    return r

def connect_to_endpoint(url, params):
    response = requests.get(url, auth=bearer_oauth, params=params)
    print(response.status_code)
    if response.status_code != 200:
        raise Exception(response.status_code, response.text)
    return response.json()


def main():
    json_response = connect_to_endpoint(search_url, query_params)
    print(json.dumps(json_response, indent=4, sort_keys=True))


if __name__ == "__main__":
    main()

